import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:iron_and_stone/data/drift/tables/castles_table.dart';
import 'package:iron_and_stone/data/drift/tables/companies_table.dart';
import 'package:iron_and_stone/data/drift/tables/matches_table.dart';

part 'app_database.g.dart';

/// Root Drift database for Iron and Stone.
///
/// Registers all three game-state tables:
/// - [MatchesTable]: match session metadata.
/// - [CastlesTable]: castle garrison and ownership snapshots.
/// - [CompaniesTable]: Company-on-map position snapshots.
///
/// Code is generated by `build_runner` — run:
///   `dart run build_runner build --delete-conflicting-outputs`
@DriftDatabase(tables: [MatchesTable, CastlesTable, CompaniesTable])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? driftDatabase(name: 'iron_and_stone'));

  /// Schema version — increment when tables change.
  @override
  int get schemaVersion => 1;
}
