import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:iron_and_stone/data/drift/tables/battles_table.dart';
import 'package:iron_and_stone/data/drift/tables/castles_table.dart';
import 'package:iron_and_stone/data/drift/tables/companies_table.dart';
import 'package:iron_and_stone/data/drift/tables/matches_table.dart';

part 'app_database.g.dart';

/// Root Drift database for Iron and Stone.
///
/// Registers all game-state tables:
/// - [MatchesTable]: match session metadata.
/// - [CastlesTable]: castle garrison and ownership snapshots.
/// - [CompaniesTable]: Company-on-map position snapshots.
/// - [BattlesTable]: active battle state snapshots.
///
/// Code is generated by `build_runner` — run:
///   `dart run build_runner build --delete-conflicting-outputs`
@DriftDatabase(tables: [MatchesTable, CastlesTable, CompaniesTable, BattlesTable])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? driftDatabase(name: 'iron_and_stone'));

  /// Schema version — increment when tables change.
  @override
  int get schemaVersion => 3;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onUpgrade: (migrator, from, to) async {
          if (from < 2) {
            // v1 → v2: add battle_id to companies and create battles table.
            await migrator.addColumn(
              companiesTable,
              companiesTable.battleId,
            );
            await migrator.createTable(battlesTable);
          }
          if (from < 3) {
            // v2 → v3: add mid-road destination columns to companies.
            await migrator.addColumn(
              companiesTable,
              companiesTable.midRoadCurrentNodeId,
            );
            await migrator.addColumn(
              companiesTable,
              companiesTable.midRoadNextNodeId,
            );
            await migrator.addColumn(
              companiesTable,
              companiesTable.midRoadProgress,
            );
          }
        },
      );
}
